# routes/assignment_maker.py

from openai import OpenAI
import os
from dotenv import load_dotenv

load_dotenv()

client = OpenAI(
    api_key=os.getenv("GROQ_API_KEY"),
    base_url="https://api.groq.com/openai/v1"
)


def write_assignment(
    topic: str,
    pages: int,
    subject: str,
    student_name: str,
    roll_no: str,
    professor: str,
    humanize: bool = True
) -> str:
    """
    Generate a complete academic assignment using Groq API.

    Args:
        topic:        The assignment topic/title.
        pages:        Approximate number of pages (1 page ≈ 350 words).
        subject:      Subject or course name.
        student_name: Student's full name (used in cover metadata only).
        roll_no:      Student's roll/seat number (used in cover metadata only).
        professor:    Professor/teacher name (used in cover metadata only).
        humanize:     If True, write in a natural human voice to bypass AI detectors.

    Returns:
        The full assignment body text as a string (no cover page — that is
        generated by the caller when building PDF/DOCX).
    """
    try:
        word_target = pages * 350

        if humanize:
            tone_instruction = (
                "Write in a natural, human academic voice. "
                "Vary sentence length deliberately — mix short punchy sentences with longer, more complex ones. "
                "Use occasional hedging phrases such as 'it appears', 'one might argue', 'this suggests', 'arguably'. "
                "Include rhetorical questions where appropriate. "
                "Vary paragraph length and structure throughout. "
                "Avoid bullet points, numbered lists, or formulaic phrasing. "
                "Do NOT use the words: delve, crucial, leverage, tapestry, multifaceted, paramount, nuanced, "
                "realm, comprehensive, intricate, pivotal, or streamline. "
                "Sound like a thoughtful, well-read university student — not an AI assistant."
            )
        else:
            tone_instruction = (
                "Write in a formal, standard academic style with consistent tone throughout."
            )

        prompt = f"""
You are an expert academic writer helping a university student complete an assignment.

Assignment Topic : {topic}
Subject / Course : {subject}
Target Length    : approximately {word_target} words ({pages} page(s))

Writing Style Instructions:
{tone_instruction}

Formatting Rules:
- Do NOT write a title page or cover page — start directly with INTRODUCTION.
- Use ALL-CAPS section headings followed by a colon (e.g. INTRODUCTION:, CONCLUSION:).
- Write in continuous prose paragraphs — no bullet points or numbered lists.
- Use smooth transitions between sections.
- Do NOT include any meta-commentary like "Here is your assignment" — write the content directly.

Structure to follow:

INTRODUCTION:
[Provide background context, state the purpose of the assignment, and present a clear thesis or central argument.]

[RELEVANT BODY SECTION TITLE IN ALL CAPS]:
[Develop the first major point with supporting evidence, examples, or analysis.]

[RELEVANT BODY SECTION TITLE IN ALL CAPS]:
[Develop the second major point.]

[RELEVANT BODY SECTION TITLE IN ALL CAPS]: (add more sections if word count allows)
[Develop the third major point.]

CONCLUSION:
[Restate the thesis, summarise key arguments, and offer a closing reflection or recommendation.]

REFERENCES:
[List 4–6 credible academic references in APA format relevant to the topic.]
"""

        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an expert academic writer. "
                        "You write complete, well-structured university assignments directly — "
                        "no preamble, no meta-commentary, no markdown code blocks. "
                        "Start immediately with INTRODUCTION:."
                    )
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            max_tokens=4000,
        )

        return response.choices[0].message.content

    except Exception as e:
        print(f"Assignment Maker Error: {e}")
        return f"Error generating assignment: {str(e)}"
